from pathlib import Path
import re

p = Path('tarnished-covenant/index.html')
s = p.read_text()

# 1) Real-image layout polish: cinematic banners instead of tall/cropped wallpaper strips.
css = r'''
/* --- Image + encounter-entry polish --- */
.tc-grace-art.tc-photo,
.tc-boss-art.tc-photo{
  width:100%;
  min-height:0 !important;
  height:auto !important;
  aspect-ratio:16/5;
  background-size:cover;
  background-repeat:no-repeat;
}
.tc-grace-art.tc-photo{background-position:center 50%;}
.tc-boss-art.tc-photo{background-position:center 44%;}
.tc-target-card{
  appearance:none;
  -webkit-appearance:none;
  width:100%;
  color:var(--ink);
  text-align:left;
  font:inherit;
  cursor:pointer;
  transition:filter .16s ease,transform .16s ease,border-color .16s ease;
}
.tc-target-card:active{transform:translateY(1px);filter:brightness(1.12)}
.tc-target-card .tc-target-enter{display:block;margin-top:8px;color:var(--gold);font-size:8px;letter-spacing:.12em;text-transform:uppercase}
@media(max-width:520px){
  .tc-grace-art.tc-photo{aspect-ratio:16/6;}
  .tc-boss-art.tc-photo{aspect-ratio:16/5.7;background-position:center 42%;}
}
'''
if '</style>' not in s:
    raise SystemExit('style marker missing')
s = s.replace('</style>', css + '\n</style>', 1)

# 2) Make the Site of Grace current-target panel itself the natural way into the encounter.
# Match the target panel generated by renderSanctuary, without depending on all surrounding markup.
pat = re.compile(
    r'<div class="tc-panel"><div class="tc-kicker">current target</div><div class="tc-value">\$\{h\(c\?\.target\?\.name\|\|\'Awaiting decree\'\)\}</div></div>'
)
replacement = '<button id="openBoss" type="button" class="tc-panel tc-target-card"><div class="tc-kicker">current target</div><div class="tc-value">${h(c?.target?.name||\'Awaiting decree\')}</div><span class="tc-target-enter">open encounter · view decree</span></button>'
s, n = pat.subn(replacement, s, count=1)
if n != 1:
    raise SystemExit('Site of Grace current-target panel not found')

# Bind that boss card after the existing hub nav/share bindings.
old = '  bindNav();bindShare();\n}\n\nfunction compactLoadout'
new = "  bindNav();bindShare();\n  document.querySelector('#openBoss')?.addEventListener('click',()=>{uiScreen='encounter';pendingRevealId=null;renderRun();});\n}\n\nfunction compactLoadout"
if old not in s:
    raise SystemExit('renderSanctuary binding marker missing')
s = s.replace(old, new, 1)

# 3) Do not let a triggered Chaos state hijack initial load / Site of Grace.
# It reveals only once the player actually enters the Encounter screen.
old_route = "if (state.current?.chaosTriggered && !acknowledgedChaos.has(state.current.id)) return renderChaosEvent();"
new_route = "if (uiScreen==='encounter' && state.current?.chaosTriggered && !acknowledgedChaos.has(state.current.id)) return renderChaosEvent();"
if old_route not in s:
    raise SystemExit('Chaos reveal route marker missing')
s = s.replace(old_route, new_route, 1)

p.write_text(s)
