from pathlib import Path
import re

p = Path('tarnished-covenant/index.html')
s = p.read_text()

# Chaos now feeds a real Favor economy, so every trigger must have a binary answer:
# it either objectively happened during the encounter or it did not.
triggers = r'''const chaosTriggers = [
  'WHEN EITHER PLAYER TAKES DAMAGE FOR THE FIRST TIME',
  'WHEN BOTH PLAYERS HAVE TAKEN DAMAGE AT LEAST ONCE',
  'WHEN SOMEBODY DRINKS THE FIRST CRIMSON FLASK',
  'WHEN THE TEAM USES ITS THIRD CRIMSON FLASK TOTAL',
  'WHEN ONE PLAYER HAS USED THREE CRIMSON FLASKS',
  'WHEN BOTH PLAYERS HAVE USED AT LEAST ONE CRIMSON FLASK',
  'WHEN BOTH PLAYERS USE A CRIMSON FLASK WITHIN FIVE SECONDS OF EACH OTHER',
  'WHEN SOMEBODY IS HIT WHILE DRINKING A FLASK',
  'WHEN THE BOSS REACHES 75% HEALTH',
  'WHEN THE BOSS REACHES 50% HEALTH',
  'WHEN THE BOSS REACHES 25% HEALTH',
  'WHEN A PLAYER FALLS BELOW 50% HEALTH FOR THE FIRST TIME',
  'WHEN A PLAYER FALLS BELOW 25% HEALTH FOR THE FIRST TIME',
  'WHEN BOTH PLAYERS ARE BELOW 50% HEALTH AT THE SAME TIME',
  'WHEN BOTH PLAYERS ARE BELOW 25% HEALTH AT THE SAME TIME',
  'WHEN EITHER PLAYER DIES',
  'AFTER THE FIRST FULL TEAM WIPE',
  'WHEN THE BOSS CAUSES THE FIRST STANCE BREAK / KNOCKDOWN ON A PLAYER',
  'WHEN THE TEAM CAUSES THE FIRST BOSS STANCE BREAK',
  'WHEN THE FIRST CRITICAL ATTACK IS LANDED ON THE BOSS',
  'WHEN ANY STATUS EFFECT PROCS ON THE BOSS',
  'WHEN ANY STATUS EFFECT PROCS ON A PLAYER',
  'WHEN THE BOSS GRABS EITHER PLAYER',
  'WHEN THE SAME PLAYER IS HIT THREE TIMES BEFORE THE OTHER PLAYER IS HIT',
  'WHEN BOTH PLAYERS ARE HIT BY THE SAME BOSS ATTACK OR AOE',
  'WHEN ONE PLAYER TAKES DAMAGE WHILE THE OTHER PLAYER IS HEALING',
  'WHEN A PLAYER HEALS WHILE THEIR PARTNER IS BELOW 25% HEALTH',
  'WHEN A PLAYER REACHES ZERO CRIMSON FLASKS',
  'WHEN THE BOSS CHANGES PHASE',
  'WHEN THE BOSS SUMMONS OR SPAWNS AN ADDITIONAL ENEMY',
  'WHEN AN ADDITIONAL ENEMY DIES DURING THE BOSS ENCOUNTER',
  'WHEN A PLAYER FALLS OR IS KNOCKED OFF THE BOSS ARENA / COMBAT AREA'
];'''

s, n = re.subn(r"const chaosTriggers = \[.*?\];", triggers, s, count=1, flags=re.S)
if n != 1:
    raise SystemExit('objective Chaos trigger target missing')

# Regression protection: subjective language cannot quietly return to this economy.
for forbidden in [
    'PANIC ROLLS',
    'WAY TOO LONG',
    'SAYS “I GOT THIS”',
    'SUSPICIOUSLY WELL',
    'EMBARRASSING AMOUNT',
    'SOMEONE SAYS “NICE”',
    'ACCIDENTALLY EMOTES',
    'MAKES THE SITUATION WORSE',
]:
    if forbidden in s:
        raise SystemExit('subjective Chaos trigger survived: ' + forbidden)

if s.count("'WHEN ") + s.count("'AFTER ") < 32:
    raise SystemExit('objective Chaos trigger pool unexpectedly small')

p.write_text(s)
